AWSTemplateFormatVersion: '2010-09-09'          # 必須的。定義了此模板遵循的CloudFormation模板版本。
Transform: AWS::Serverless-2016-10-31           # 必須的。指定此模板使用的SAM規範版本。

Description: An example SAM template for a Java application

Globals:
  Function:
    Timeout: 10

Resources:
  UploadMusicFunction:  # Lambda函數名稱。
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.mycompany.UploadMusicHandler
      Runtime: java8.al2
      CodeUri: target/demospotify-clone-0.0.1-SNAPSHOT.jar
      Events:
        UploadMusicApi:  # 事件名稱。
          Type: Api
          Properties:
            Path: /upload
            Method: post  # 通常上傳會使用POST方法。

  ListenMusicFunction:  # 另一個Lambda函數名稱。
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.mycompany.ListenMusicHandler
      Runtime: java8.al2
      CodeUri: target/demospotify-clone-0.0.1-SNAPSHOT.jar
      Events:
        ListenMusicApi:  # 事件名稱。
          Type: Api
          Properties:
            Path: /listen/{songId}  # 假設URL中有songId參數。
            Method: get

Outputs:
  UploadMusicApi:
    Description: "API Gateway endpoint URL for Prod environment for Upload"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"

  ListenMusicApi:
    Description: "API Gateway endpoint URL for Prod environment for Listen"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/listen/{songId}"

