AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-spotify-clone

  Sample SAM Template for sam-spotify-clone

Resources:
  GetPresignedUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetPresignedUrlsFunction
      Handler: com.spotifyclone.demospotifyclone.Lambda.LambdaHandlers$GetPresignedUrlsLambdaHandler
      Runtime: java8  
      MemorySize: 512
      Timeout: 10
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /presigned-url
            Method: post

  SaveSongToDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SaveSongToDbFunction
      Handler: com.spotifyclone.demospotifyclone.Lambda.LambdaHandlers$SaveSongToDbLambdaHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 10
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /save-song
            Method: post

  GetAllAlbumsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAllAlbumsFunction
      Handler: com.spotifyclone.demospotifyclone.Lambda.LambdaHandlers$GetAllAlbumsLambdaHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 10
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /albums
            Method: get

    MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: spotify_clone_mason_3
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: postgres
      MasterUsername: mason
      MasterUserPassword: cleverice007
      MultiAZ: false

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: spotify-clone-mason

  # Policies to allow Lambda functions to interact with S3 and RDS
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: S3AndRDSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - arn:aws:s3:::spotify-clone-mason/*
              - Effect: Allow
                Action:
                  - rds:*
                Resource:
                  - !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:MyRDSInstance'



Outputs:
  GetPresignedUrlsApi:
    Description: API Gateway endpoint for GetPresignedUrls function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/presigned-url/"

  SaveSongToDbApi:
    Description: API Gateway endpoint for SaveSongToDb function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save-song/"

  GetAllAlbumsApi:
    Description: API Gateway endpoint for GetAllAlbums function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/albums/"

