AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-spotify-clone

Globals:
  Function:
    Timeout: 10
    Runtime: java8
    MemorySize: 512
    CodeUri: HelloWorldFunction/

Resources:
  MyServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST,GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  GetPresignedUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetPresignedUrlsFunction
      Handler: com.spotifyclone.demospotifyclone.Lambda.LambdaHandlers$GetPresignedUrlsLambdaHandler
      Events:
        PostPresignedUrlEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyServerlessApi
            Path: /presigned-url
            Method: post
      Environment:
        Variables:
          BUCKET_NAME: spotify-clone-mason

  SaveSongToDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SaveSongToDbFunction
      Handler: com.spotifyclone.demospotifyclone.Lambda.LambdaHandlers$SaveSongToDbLambdaHandler
      Events:
        SaveSongEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyServerlessApi
            Path: /save-song
            Method: post
      Environment:
        Variables:
          BUCKET_NAME: spotify-clone-mason
          DB_INSTANCE_NAME: spotify_clone_mason_3

  GetAllAlbumsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAllAlbumsFunction
      Handler: com.spotifyclone.demospotifyclone.Lambda.LambdaHandlers$GetAllAlbumsLambdaHandler
      Events:
        ListAlbumsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyServerlessApi
            Path: /albums
            Method: get
      Environment:
        Variables:
          DB_INSTANCE_NAME: spotify_clone_mason_3

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AndRDSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: arn:aws:s3:::spotify-clone-mason/*
              - Effect: Allow
                Action: rds:*
                Resource: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:spotify_clone_mason_3'

Outputs:
  GetPresignedUrlsApi:
    Description: "API Gateway endpoint URL for GetPresignedUrls function"
    Value: !Sub "https://${MyServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/presigned-url/"
  
  SaveSongToDbApi:
    Description: "API Gateway endpoint URL for SaveSongToDb function"
    Value: !Sub "https://${MyServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save-song/"
  
  GetAllAlbumsApi:
    Description: "API Gateway endpoint URL for GetAllAlbums function"
    Value: !Sub "https://${MyServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/albums/"

